[package]
name = "skilldock"
version = "1.0.14"
description = "SkillDock desktop app"
authors = ["SkillDock"]
license = "MIT"
repository = "https://github.com/wanghuan9/skilldock"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "skilldock_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
serde_json = "1.0"
serde_yml = "0.0.12"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.10.3", features = [] }
tauri-plugin-log = "2"
tauri-plugin-dialog = "2"
url = "2.5"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "multipart", "rustls-tls"] }
regex = "1.11"
zip = { version = "2", default-features = false, features = ["deflate"] }
json5 = "0.4"
jsonc-parser = { version = "0.33", features = ["cst"] }
toml_edit = "0.22"
base64 = "0.22"
chrono = { version = "0.4", default-features = false, features = ["std", "clock"] }
sha2 = "0.10"
tauri-plugin-updater = "2.10.1"
tauri-plugin-process = "2.3.1"
notify = "6.1"
uuid = { version = "1", features = ["v4"] }
fs2 = "0.4"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_Storage_FileSystem"] }
